### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Dagar175** [VapiAI/docs-archived#131]
path---------------------> https://docs.vapi.ai/assistants/dynamic-variables

##Page is not loading##
!Attachments --> (https://github.com/user-attachments/assets/5420ed40-6a9b-4b6a-a9fb-8678f721543b)

ReferenceError: variableName is not defined
    at _createMdxContent (eval at <anonymous> (6965-f53a191f6341ede2.js:96:2561), <anonymous>:326:9)
    at MDXContent (eval at <anonymous> (6965-f53a191f6341ede2.js:96:2561), <anonymous>:335:9)
    at lk (framework-17ccb96b341e961c.js:1:130166)
    at i (framework-17ccb96b341e961c.js:1:188682)
    at uD (framework-17ccb96b341e961c.js:1:168335)
    at framework-17ccb96b341e961c.js:1:168202
    at uI (framework-17ccb96b341e961c.js:1:168209)
    at uE (framework-17ccb96b341e961c.js:1:164961)
    at ux (framework-17ccb96b341e961c.js:1:163516)
    at x (framework-17ccb96b341e961c.js:1:206913)

**Comment by sahilsuman933** [comment]
Fixed. Thanks!
